####################################
# Shared runtime image
FROM ruby:2.6.6-slim-stretch as runtime

RUN useradd -m -U app \
 && su -s /bin/bash -c "mkdir -p /home/app/vendor/gems" app

ENV RUNTIME_DEPS="git imagemagick libexif12 libexpat1 libgif7 glib-2.0 libgsf-1-114 libjpeg62-turbo libpng16-16 libpoppler-glib8 libpq5 libreoffice-core librsvg2-2 libsqlite3-0 libtiff5 libwrap0 libyaz4 locales mediainfo nodejs openjdk-8-jre-headless shared-mime-info sudo tzdata yarn" \
    DEBIAN_FRONTEND="noninteractive" \
    RAILS_ENV="production" \
    LANG="en_US.UTF-8"

RUN mkdir /usr/share/man/man1 \
 && apt-get update -qq \
 && apt-get install -y curl gnupg2 apt-transport-https ca-certificates --no-install-recommends \
 && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
 && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
 && echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
 && curl -LO https://mediaarea.net/repo/deb/repo-mediaarea_1.0-16_all.deb \
 && dpkg -i repo-mediaarea_1.0-16_all.deb \
 && rm repo-mediaarea_1.0-16_all.deb \
 && apt-get update -qq \
 && apt-get install -y $RUNTIME_DEPS --no-install-recommends \
 && apt-get clean -y \
 && rm -rf /var/lib/apt/lists/* \
 && alias nodejs=node \
 && yarn add webpack \
 && dpkg-reconfigure -f noninteractive tzdata \
 && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
 && echo 'LANG="en_US.UTF-8"' > /etc/default/locale \
 && dpkg-reconfigure --frontend=noninteractive locales \
 && update-locale LANG=en_US.UTF-8

# Install FFMPEG
RUN mkdir -p /tmp/ffmpeg/bin \
 && cd /tmp/ffmpeg \
 && curl https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz | tar xJ \
 && cp $(find . -type f -executable) /usr/local/bin/

RUN gem update --system
