default: &default
  adapter: postgresql
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DB_USER") { "docker" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "d0ck3r" } %>

development:
  <<: *default
  database: avr-development

test:
  <<: *default
  database: avr-test

production:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/production.sqlite3
