---
e3285bfcd6cb4332a84aa14da6a3eaad:
  :uid: :user_id
  :email: :lis_person_contact_email_primary
  :context_id: :context_id
  :context_name: :context_title
7db438071375c02373713c12c73869ff2f470b68.new-northwestern.instructure.com:
  :uid: :lis_person_sourcedid
  :email: :lis_person_contact_email_primary
  :context_id: :context_label
  :context_name: :context_title
avalon.ares.atlas-sys.com:
  :uid: :lis_person_sourcedid
  :email: :lis_person_contact_email_primary
  :context_id: :context_id
  :context_name: :context_title
