---
active_job:
  queue_adapter: inline
localstack: {}
matterhorn:
  root: http://matterhorn:8080/
  baseApplication: avalon
  cleanup_log: log/cleanup_jobs.log
  media_path: "/masterfiles"
redis:
  port: 6380
streaming:
  server: :nginx
  stream_token_ttl: 20
  content_path: "/streamfiles"
  rtmp_base: rtmp://streaming/avalon
  http_base: http://streaming:8880/avalon
  default_quality: low
domain:
  host: devbox.library.northwestern.edu
  port: 3000
  protocol: https
dropbox:
  path: "/masterfiles/dropbox"
  upload_uri: file:///masterfiles/dropbox
solrcloud: true
zookeeper:
  connection_str: localhost:9983/configs
