domain:
  host: test.host
dropbox:
  upload_uri: smb://test.host/dropbox
auth:
  configuration:
  - :name: Avalon Test Auth
    :provider: :identity
    :params:
      :fields:
      - :email
  - :name: Avalon Lti OAuth
    :provider: :lti
    :hidden: true
    :params:
      :oauth_credentials:
        key: 'secret'
redis:
  post: 6381
streaming:
  server: :generic
  stream_token_ttl: 20 #minutes
  content_path: '/srv/avalon/content'
  rtmp_base: 'rtmp://localhost:1937/avalon'
  http_base: 'http://localhost:8882/avalon'
  default_quality: 'low'
matterhorn:
  root: 'http://localhost:8082/'
  baseApplication: 'avalon'
  cleanup_log: 'log/cleanup_jobs.log'
zookeeper:
  connection_str: "localhost:9985/configs"
