---
name: Check Terraform Style
on: [push]
jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v1
        name: Setup tflint
        with:
          tflint_version: v0.52.0
      - name: Show version
        run: tflint --version

      - name: Check Terraform Manifests
        run: |
          terraform init -backend=false -input=false
          tflint --init
          tflint -f compact
        working-directory: ./terraform
